# Generated by Django 5.1.1 on 2024-09-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_costo_alter_producto_precio_venta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='costo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
