# Generated by Django 5.1.1 on 2024-09-19 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_costo_alter_producto_precio_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('raza', models.CharField(max_length=100)),
                ('procedencia', models.CharField(max_length=100)),
            ],
        ),
    ]
